name: Test
on: workflow_dispatch
jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.step1_variable_2 }}
      output2: ${{ steps.step2.outputs.step2_variable }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Setup Python
        id: python
        uses: actions/setup-python@v4.7.1
      - name: Generate Step 1 Outputs (10 & 11)
        id: step1
        run: |
          echo "step1_variable_1=10" >> $GITHUB_OUTPUT
          echo "step1_variable_2=11" >> $GITHUB_OUTPUT
      - id: step2
        name: Display Step 1 Outputs (10 & 11) and Generate Step 2 Output (12)
        run: |
          echo "Step 1 variable 1 is ${{steps.step1.outputs.step1_variable_1}}"
          echo "Step 1 variable 2 is ${{steps.step1.outputs.step1_variable_2}}"
          echo "step2_variable=12" >> $GITHUB_OUTPUT
          
      - name: Python "share_complex_data.py" as Executable
        run: chmod +x scripts/share_complex_data.py
      - name: Generate Complex Data from Python
        shell: bash
        run: python scripts/share_complex_data.py > output.log
      - name: Share Complex Data as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-file
          path: output.log
      - name: Download Complex Data Between Steps
        uses: actions/download-artifact@v3
        with:
          name: output-file
      - name: Print downloaded Complex Data
        run: cat output.log
  job2:
    name: Job 2
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Setup Python
        id: python
        uses: actions/setup-python@v4.7.1
      - name: Print Shared Variables from Job 1
        run: |
          echo "Job 1 output 1 is ${{needs.job1.outputs.output1}}"
          echo "Job 1 output 2 is ${{needs.job1.outputs.output2}}"
      - name: Python "consume_variables.py" as Executable
        run: chmod +x scripts/consume_variables.py
      - name: Consume Shared Varibles with Python
        run: |
          python scripts/consume_variables.py ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
      - name: Download Complex Data Between Jobs
        uses: actions/download-artifact@v3
        with:
          name: output-file
      - name: Print downloaded Complex Data
        run: cat output.log
    
