name: Test
on: workflow_dispatch
jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.step1_variable_2 }}
      output2: ${{ steps.step2.outputs.step2_variable }}
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: step1
        name: Step 1
        run: |
          echo "step1_variable_1=10" >> $GITHUB_OUTPUT
          echo "step1_variable_2=11" >> $GITHUB_OUTPUT
      - id: step2
        name: Step 2
        run: |
          echo "Step 1 variable 1 is ${{steps.step1.outputs.step1_variable_1}}"
          echo "Step 1 variable 2 is ${{steps.step1.outputs.step1_variable_2}}"
          echo "step2_variable=12" >> $GITHUB_OUTPUT
  job2:
    name: Job 2
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Setup Python
        id: python
        uses: actions/setup-python@v4.7.1
      - run: |
          echo "Job 1 output 1 is ${{needs.job1.outputs.output1}}"
          echo "Job 1 output 2 is ${{needs.job1.outputs.output2}}"
      - run: chmod +x scripts/consume_variables.py
      - run: |
          python scripts/consume_variables.py ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
    
